### PR TITLE
lld v13.0.1 (redux)

### PR DESCRIPTION
**Pull request by h-vetinari**
Rebased #31 against master

Closes #32 (hopefully)
Closes #31 
Closes #30 
Closes #29

### CODE REVIEW

**Comment by h-vetinari** [comment]
Waiting for builds from https://github.com/conda-forge/llvmdev-feedstock/pull/140 (CI didn't trigger on merge)

**Comment by h-vetinari** [comment]
Note, this PR still has some debug commits and should probably not be merged as-is.
* Luckily, the windows failure from #31 is gone (so we can revert https://github.com/conda-forge/lld-feedstock/pull/33/commits/7c655767ec28f33dcd68de0deaac19ce84ea2938 and maybe also https://github.com/conda-forge/lld-feedstock/pull/33/commits/81a871d7fe91c19f7cf2a0280a15995f7c5d9b59) - fingers crossed that the rest of the build succeeds as well
* For OSX, https://github.com/conda-forge/lld-feedstock/pull/33/commits/6ae10da2b7a5079faec7631efd5c748a05e22ea5 is worth noting as raising the minimum OSX SDK to 10.13. I tried in #31 to avoid that, but without success. Here's a summary:
  > I think the xar issues (same as in #30) might be due to a recent [addition](https://github.com/llvm/llvm-project/commit/ca6751043d8899b12baeb48621e61fb352cfee09). In any case, they fail with MACOS_SDK 10.12 (despite `LLVM_HAVE_LIBXAR`), but pass with 10.13 & 10.14.
  > 
  > It's also worth noting that xar has been deprecated since MACOSX_SDK 12.0, and upstream [warns](https://github.com/llvm/llvm-project/commit/d321548c3ce987f4f21350ba1c81fdb5d4354224) since LLVM 14 that `LLVM_HAVE_LIBXAR` might be removed in the future.

**Comment by h-vetinari** [comment]
Alright, this is ready except for a clean-up of the commit history. The one outstanding question is that it requires bumping `MACOSX_DEPLOYMENT_TARGET` to 10.13 - below that there are errors with xar symbols that I couldn't solve, even with LLVM_HAVE_LIBXAR (see previous comment).

CC @conda-forge/lld

**Comment by isuruf** [comment]
I think we should build `libxar` ourselves.

**Comment by h-vetinari** [comment]
> I think we should build `libxar` ourselves.

Seems the original [project](https://code.google.com/archive/p/xar/) has been very dead for a while; curiously this [fork](https://github.com/mackyle/xar) has continued with minting new releases a bit longer, but even the last release is close to 10 years old. Which one do you prefer?

This is to support MACOSX_DEPLOYMENT_TARGET  10.9 - 10.12, right? I.e. not necessary anywhere else? I can try to see if it builds for osx-64...

**Comment by isuruf** [comment]
I was thinking of the sources from apple at https://opensource.apple.com/tarballs/xar/

**Comment by isuruf** [comment]
> This is to support MACOSX_DEPLOYMENT_TARGET 10.9 - 10.12, right? I.e. not necessary anywhere else? I can try to see if it builds for osx-64...

Yes, and also for linux I guess.

**Comment by h-vetinari** [comment]
> I was thinking of the sources from apple at https://opensource.apple.com/tarballs/xar/

OK. Which version to start with? Will we need to build an old version to be (ABI-?)compatible with the libxar that's in the old SDKs? Wouldn't the fact that it's part of those SDKs potentially mean migrating every osx-package against libxar?

**Comment by isuruf** [comment]
Latest would be fine. I don't think there'd be any ABI compatibility issues and I doubt there are other packages using it.

**Pull request closed without merging**
