### PR TITLE
lld v13.0.0 (redux)

### PR DESCRIPTION
**Pull request by h-vetinari**
Closes #29

Also add myself to maintainers as discussed [here](https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/69#issuecomment-933036007).

### CODE REVIEW

**Comment by h-vetinari** [comment]
OK, I first got some google hits that suggested the missing symbols are in `libxml2`, but it looks like we need libxar. It doesn't seem to have a feedstock, but the closest I found is in ld64 ([1](https://github.com/conda-forge/cctools-and-ld64-feedstock/blob/41e56d1b1e5aa3ab8d6cb04b8119e29a1f2c751e/recipe/meta.yaml#L39) [2](https://github.com/conda-forge/cctools-and-ld64-feedstock/blob/41e56d1b1e5aa3ab8d6cb04b8119e29a1f2c751e/recipe/meta.yaml#L100))

**Comment by isuruf** [comment]
libxar is in the macos SDK

**Comment by h-vetinari** [comment]
> 
> 
> libxar is in the macos SDK

Any idea why it isn't being found?

**Comment by h-vetinari** [comment]
Thanks a lot. I had found `LLVM_HAVE_LIBXAR` [upstream](https://github.com/llvm/llvm-project/blob/release/13.x/lld/MachO/SyntheticSections.cpp#L1267), but thought (wrongly...) that this would be picked up by CMake et al.

I rebased the PR to remove the false addition of libxml2.

**Comment by h-vetinari** [comment]
Welp... Xar symbols still not found 😑

**Comment by h-vetinari** [comment]
`lld-link /?` seems to hang on windows (happened in previous run as well that already got deleted by azure)

**Pull request closed without merging**
