### PR TITLE
add wasm-lld build

### PR DESCRIPTION
**Pull request by wolfv**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This enables wasm support in lld and, together with Binaryen and an upcoming emscripten recipe, will allow for webassembly compilation on conda-forge.

We could also put wasm-lld into the main output. Up to you, @isuruf.

### CODE REVIEW

**Review by isuruf — CHANGES_REQUESTED** [review]
This is already in the build.  What are you trying to achieve here?

**Comment by wolfv** [comment]
funny, I didn't see it :) guess we can close this then

**Comment by jakirkham** [comment]
Yep exactly. I think the pieces for WASM started showing up in LLVM 8 and have been added to since. Given we are a number of releases in, wouldn't be surprised to learn everything we need is already here.

That said, I think we still need to build [WASM's `libc` ]( https://github.com/WebAssembly/wasi-libc ) (basically a `musl` fork) so that we are able to build C libraries. AIUI the C++ library is already covered by `libc++` ( https://github.com/WebAssembly/design/issues/1228 ).

**Comment by wolfv** [comment]
that is automatically done by emscripten, but we can (and should) cache this. I can take care of this in the emscripten recipe.

**Comment by jakirkham** [comment]
Yeah I guess it is a question of whether we want to use Emscripten, which is slowly being replaced by LLVM, or if we want to just start with LLVM out of the gate. Initially had thought the latter made sense, but I guess this is more up to those driving this work today 🙂

**Pull request closed without merging**
